# Generated by Django 2.2 on 2019-04-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
